### ISSUE TITLE
error when run doHMRF

### ISSUE THREAD

**Issue by Huimin721** [giotto-suite/Giotto#125]
Hi,

I just run the example code in mini seqFISH page,

seqfish_mini = addHMRF(gobject = seqfish_mini,
                       HMRFoutput = HMRF_spatial_genes,
                       k = 9, betas_to_add = c(28),
                       hmrf_name = 'HMRF')

it turns that:
expression_matrix.txt already exists at this location, will be overwritten 

 spatial_genes.txt already exists at this location, will be overwritten 

 spatial_network.txt already exists at this location, will be overwritten 

 spatial_cell_locations.txt already exists at this location, will be overwritten 
[1] "/Users/Huimin/Library/r-miniconda/envs/giotto_env/bin/pythonw /Library/Frameworks/R.framework/Versions/4.1/Resources/library/Giotto/python/reader2.py -l \"~/Temp//11_HMRF//Spatial_genes/SG_top100_k9_scaled/spatial_cell_locations.txt\" -g \"~/Temp//11_HMRF//Spatial_genes/SG_top100_k9_scaled/spatial_genes.txt\" -n \"~/Temp//11_HMRF//Spatial_genes/SG_top100_k9_scaled/spatial_network.txt\" -e \"~/Temp//11_HMRF//Spatial_genes/SG_top100_k9_scaled/expression_matrix.txt\" -o \"~/Temp//11_HMRF//Spatial_genes/SG_top100_k9_scaled/result.spatial.zscore\" -a test -k 9 -b 28 2 2 -t 1e-10 -z none -s 100 -i 100"
Traceback (most recent call last):
  File "/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Giotto/python/reader2.py", line 141, in <module>
    mat, genes, cells = read_expression_classic(args.expression)
  File "/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Giotto/python/reader2.py", line 68, in read_expression_classic
    f = open(n)
FileNotFoundError: [Errno 2] No such file or directory: '~/Temp//11_HMRF//Spatial_genes/SG_top100_k9_scaled/expression_matrix.txt'

My Rstudio version is 4.1.0 and Giotto version is 1.0.4, I run the code on Mac iOS Big Sur 11.3. Could you please help me with that? Thank you!

**Comment by bernard2012** [comment]
Could you test Giotto in the docker image, and check if the same issue occurs in the Docker image? If the issue does not appear there, then it may be due to the specific Mac OS set up.
