### ISSUE TITLE
Function to convert Giotto object to anndata object！

### ISSUE THREAD

**Issue by Jiahe-Sun** [giotto-suite/Giotto#638]
Hello, 
I have observed that giotto provides a function to convert anndata object to Giotto object, but there is no function to convert Giotto object to anndata object. 

There is a great need for this function in the research, and I hope to add this function as soon as possible.

(Note: I don't know how to save giotto objects after using giotto analysis and would like your guidance.)

**Comment by mattobny** [comment]
Hello @sunjiahe-hub,

Giotto has provided functions for both converting to and from AnnData since v3.1. These functions, `anndataToGiotto()` and `giottoToAnnData()`, exist on the `suite` branch and are being extended in the `suite_dev` branch. 

You can save your Giotto Object as a .RDS file using `saveGiotto()`. Below is the source code for this function, along with its documentation.

https://github.com/drieslab/Giotto/blob/2e3e46f46f1c505e97308242581980a433549922/R/general_help.R#L815-L840

Please let me know if I can be of any further assistance!

**Comment by sunjiahe-hub** [comment]
Thank you very much for your reply. 

Can I understand that "RubD/ Giotto@suite "is the latest version of Giotto and will replace "RubD/Giotto" in the future?

The installation and use of "RubD/ Giotto@suite "is different from that of "RubD/Giotto".

**Comment by sunjiahe-hub** [comment]
Thank you very much for your reply!

Can I understand that "RubD/ Giotto@suite "is the latest version of Giotto, because it has not been officially released at present, if it is officially released, it will replace the original version of Giotto in the future ("RubD/Giotto")?

The installation and use of "RubD/ Giotto@suite "is different from that of "RubD/Giotto", leading me to fail to understand the difference between Giotto@suite and Giotto.

Hope to get your reply, sincere thanks

**Comment by Jiahe-Sun** [comment]
> 你好@sunjiahe-hub,
> 
> 自 v3.1 以来，Giotto 提供了与 AnnData 相互转换的功能。这些功能，`anndataToGiotto()`和`giottoToAnnData()`，存在于`suite`分支上，并正在`suite_dev`分支中进行扩展。
> 
> 您可以使用 将 Giotto 对象保存为 .RDS 文件`saveGiotto()`。下面是此函数的源代码及其文档。
> 
> https://github.com/drieslab/Giotto/blob/2e3e46f46f1c505e97308242581980a433549922/R/general_help.R#L815-L840
> 
> 如果我能提供任何进一步的帮助，请告诉我！

Thank you very much for your reply!
I would like your guidance on two questions:
1. Can I understand that "RubD/ Giotto@suite "is the latest version of Giotto, because it has not been officially released at present, if officially released, it will replace the previous version of Giotto in the future ("RubD/Giotto")?

2. Currently I can only install Giotto V3.0.1 using the "remotes::install_github("RubD/Giotto@suite")" command. How do I download and install V3.1? Currently in the making library (https://github.com/drieslab/Giotto) cannot be retrieved about "giottoToAnnData ()" function relevant information.

Hope to get your reply, sincere thanks

**Comment by Jiahe-Sun** [comment]
Looking forward to the release of the new version！
My research needs to use the "giottoToAnnData( )" function to convert a Giotto object to an anndata object;

**Comment by mattobny** [comment]
@sunjiahe-hub Your understanding is partially correct; `drieslab/Giotto@suite` is the most current stable release of Giotto. Although this is not referenced properly in the `Releases` tab (many apologies, this will be amended soon), we are currently on v3.2. If you have already installed Giotto Suite, can you load the package, i.e. `library(Giotto)`, and then provide the output to `sessionInfo()`?

If you believe the incorrect version is installed, please provide the above info, and then try reinstalling with `devtools::install_github("drieslab/Giotto@suite")`. This should download and install the most current code from the repository. Running `sessionInfo()` after loading the package will show if the install of the appropriate version was successful.

As a side note, we tentatively plan to change the default branch (currently `master`) to `suite`, as we are actively developing Giotto Suite, which extends and improves Giotto (which lives on the branch `master`). We will communicate this change when necessary.

**Comment by mattobny** [comment]
@sunjiahe-hub Closing this issue with the recent version bump of Giotto Suite to v3.3, as updated anndata conversion scripts are live. If the installation issue persists, please submit another issue and we will gladly assist you!

**Comment by Jiahe-Sun** [comment]
thank you.

**Comment by Jiahe-Sun** [comment]
Hello, thank you very much for your reply. I hope Giotto can have a good ecological environment! 

I would like your help with two questions:

1: I checked the code of "giottoToAnnData()" function and found that it has no slot for storing pictures. May I ask how pictures can be stored in anndata, especially in the case of multiple pictures?

2: I successfully installed the Giotto package, but failed to Install the Giotto Python Environment. The error is as follows: I tried to configure the Giotto python environment on different servers and specify the Python path, but it still cannot be used normally. I am not sure whether it is the problem of Giotto. I hope you can get help. Thanks again!



Install the Giotto Python Environment error: Install the Giotto Python environment error:
`Downloading and Extracting Packages

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
+ . /home/sgs/.local/share/r-miniconda/bin/activate
+ conda activate '/home/sgs/.local/share/r-miniconda/envs/giotto_env'
+ '/home/sgs/.local/share/r-miniconda/envs/giotto_env/bin/python' -m pip install --upgrade --no-user 'smfishhmrf' 'python-louvain==0.16'
Collecting smfishhmrf
  Using cached smfishHmrf-1.3.3-py3-none-any.whl (51 kB)
Collecting python-louvain==0.16
  Using cached python-louvain-0.16.tar.gz (204 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: networkx in /home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages (from python-louvain==0.16) (2.8.8)
Requirement already satisfied: numpy in /home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages (from python-louvain==0.16) (1.24.2)
Requirement already satisfied: scipy in /home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages (from smfishhmrf) (1.10.1)
Requirement already satisfied: pandas in /home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages (from smfishhmrf) (1.5.1)
Collecting seaborn (from smfishhmrf)
  Using cached seaborn-0.12.2-py3-none-any.whl (293 kB)
Collecting matplotlib (from smfishhmrf)
  Downloading matplotlib-3.7.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 24.4 kB/s eta 0:00:00
Collecting contourpy>=1.0.1 (from matplotlib->smfishhmrf)
  Downloading contourpy-1.0.7-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (300 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 300.3/300.3 kB 20.1 kB/s eta 0:00:00
Collecting cycler>=0.10 (from matplotlib->smfishhmrf)
  Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting fonttools>=4.22.0 (from matplotlib->smfishhmrf)
  Downloading fonttools-4.39.3-py3-none-any.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 20.3 kB/s eta 0:00:00
Collecting kiwisolver>=1.0.1 (from matplotlib->smfishhmrf)
  Downloading kiwisolver-1.4.4-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 22.9 kB/s eta 0:00:00
Requirement already satisfied: packaging>=20.0 in /home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages (from matplotlib->smfishhmrf) (23.1)
INFO: pip is looking at multiple versions of matplotlib to determine which version is compatible with other requirements. This could take a while.
Collecting matplotlib (from smfishhmrf)
  Downloading matplotlib-3.7.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 19.2 kB/s eta 0:00:00
  Downloading matplotlib-3.6.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 27.7 kB/s eta 0:00:00
  Downloading matplotlib-3.6.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 19.9 kB/s eta 0:00:00
  Downloading matplotlib-3.6.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 21.3 kB/s eta 0:00:00
  Downloading matplotlib-3.6.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.8 MB)
                                              0.1/11.8 MB 25.2 kB/s eta 0:07:45
ERROR: Exception:
Traceback (most recent call last):
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/http/client.py", line 465, in read
    s = self.fp.read(amt)
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/ssl.py", line 1273, in recv_into
    return self.read(nbytes, buffer)
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/ssl.py", line 1129, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 237, in _attempt_to_pin_criterion
    for candidate in criterion.candidates:
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
    super().__init__(
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 587, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_internal/network/download.py", line 147, in __call__
    for chunk in chunks:
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
    with self._error_catcher():
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/sgs/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
Error: Error installing package(s): "'smfishhmrf'", "'python-louvain==0.16'"`
