### ISSUE TITLE
Installation error on CentOS cluster

### ISSUE THREAD

**Issue by rbutleriii** [giotto-suite/Giotto#839]
**Describe the Error**

Failed installation on a CentOS cluster. Tried multiple methods, but including reticulate and non-reticulate installations, centers around liedenalg and sklearn packages not working. I tried pushing ahead, and it errors missing some glibc libraries...? The `lmod` R distribution is run by the admins, so I cannot update gcc/glibc for R. Installing conda's version of gcc in the `giotto_env` does not appear to help. 

...

**Error Message**

```r
> pkg_check()
/home/rrbutler/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/rrbutler/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/home/rrbutler/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/rrbutler/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
leidenalg was not found within environment:
 /home/rrbutler/.local/share/r-miniconda/envs/giotto_env/bin/python

sklearn was not found within environment:
 /home/rrbutler/.local/share/r-miniconda/envs/giotto_env/bin/python

[1] "leidenalg" "sklearn"
```
Since those are missing, I can run the `retry_install` in [6. Troubleshooting Packages not Found](https://giottosuite.readthedocs.io/en/latest/subsections/datasets/configuration_04122023.html#troubleshooting-packages-not-found), and get the following:

```r
Error: Specified conda binary '/home/rrbutler/.local/share/r-miniconda/envs/giotto_env/bin/conda' does not exist.
```
Which is true, it does not. I wonder if that is a component of `python.app` ? When I tried installing independently via conda with the `.yml` it recommended:
```sh
Unable to install package for python.app==1.4.

Please double check and ensure your dependencies file has
the correct spelling.  You might also try installing the
conda-env-python.app==1.4 package to see if provides the required
installer.
``` 
If I just push ahead anyways with the clustering tutorial, it will crash out at Leiden:
```r
> testobj <- doLeidenCluster(gobject = testobj,
+                             resolution = 0.4,
+                             n_iterations = 1000,
+                             name = 'leiden_0.4_1000')
Error in py_run_file_impl(file, local, convert) :
  ImportError: /scg/apps/software/r/4.2.2/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/rrbutler/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/leidenalg/../../../libigraph.so.3)
Run `reticulate::py_last_error()` for details.
> reticulate::py_last_error()

── Python Exception Message ─────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/home/rrbutler/R/x86_64-pc-linux-gnu-library/4.2/Giotto/python/python_leiden.py", line 10, in <module>
    import leidenalg as la
  File "/scg/apps/software/r/4.2.2/lib/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/scg/apps/software/r/4.2.2/lib/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/scg/apps/software/r/4.2.2/lib/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/home/rrbutler/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/leidenalg/__init__.py", line 35, in <module>
    from .functions import ALL_COMMS
  File "/scg/apps/software/r/4.2.2/lib/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/scg/apps/software/r/4.2.2/lib/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/scg/apps/software/r/4.2.2/lib/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/home/rrbutler/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/leidenalg/functions.py", line 3, in <module>
    from . import _c_leiden
  File "/scg/apps/software/r/4.2.2/lib/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/scg/apps/software/r/4.2.2/lib/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/scg/apps/software/r/4.2.2/lib/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
ImportError: /scg/apps/software/r/4.2.2/lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/rrbutler/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/leidenalg/../../../libigraph.so.3)

── R Traceback ──────────────────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─Giotto::doLeidenCluster(...)
 2.   └─reticulate::source_python(file = python_leiden_function)
 3.     └─reticulate::py_run_file(file, local = FALSE, convert = convert)
 4.       └─reticulate:::py_run_file_impl(file, local, convert)

```

**To Reproduce**

Default install using the Tutorials on a cluster using an `lmod` setup to load shared R distributiuons. (load R with `ml R/4.2.2`). This is R not Rstudio

**System Information**
- OS: CentOS Linux 7
    - Version 7
    - R 4.2.2
    - Giotto 4.0.0 
    - Python 3.10.2
```r
> checkGiottoEnvironment()

 giotto environment found at
/home/rrbutler/.local/share/r-miniconda/envs/giotto_env/bin/python

[1] TRUE

> reticulate::py_config()
python:         /home/rrbutler/.local/share/r-miniconda/envs/giotto_env/bin/python
libpython:      /home/rrbutler/.local/share/r-miniconda/envs/giotto_env/lib/libpython3.10.so
pythonhome:     /home/rrbutler/.local/share/r-miniconda/envs/giotto_env:/home/rrbutler/.local/share/r-miniconda/envs/giotto_env
version:        3.10.2 | packaged by conda-forge | (main, Mar  8 2022, 15:53:57) [GCC 9.4.0]
numpy:          /home/rrbutler/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/numpy
numpy_version:  1.26.2
pandas:         /home/rrbutler/.local/share/r-miniconda/envs/giotto_env/lib/python3.10/site-packages/pandas

NOTE: Python version was forced by use_python() function


> sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblas-r0.3.3.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] GiottoData_0.2.6.2  Giotto_4.0.0        GiottoVisuals_0.1.0
[4] GiottoClass_0.1.0   GiottoUtils_0.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.11       magrittr_2.0.3    rappdirs_0.3.3    tidyselect_1.2.0
 [5] munsell_0.5.0     colorspace_2.1-0  lattice_0.22-5    R6_2.5.1
 [9] rlang_1.1.2       fansi_1.0.5       colorRamp2_0.1.0  dplyr_1.1.4
[13] tools_4.2.2       parallel_4.2.2    grid_4.2.2        checkmate_2.3.0
[17] data.table_1.14.8 gtable_0.3.4      png_0.1-8         utf8_1.2.4
[21] terra_1.7-55      cli_3.6.1         withr_2.5.2       tibble_3.2.1
[25] lifecycle_1.0.4   Matrix_1.6-1.1    ggplot2_3.4.4     vctrs_0.6.5
[29] codetools_0.2-19  glue_1.6.2        compiler_4.2.2    pillar_1.9.0
[33] generics_0.1.3    scales_1.3.0      backports_1.4.1   jsonlite_1.8.8
[37] reticulate_1.34.0 pkgconfig_2.0.3
```

**Comment by rbutleriii** [comment]
leidenalg and sklearn are installed in the giotto_env, it seems like it is just the missing library?

```sh
(giotto_env) rrbutler@smsh11dsu-srcf-d15-35 [Sat Dec 09 16:37:31] 6 Analysis$ conda list
# packages in environment at /home/rrbutler/.local/share/r-miniconda/envs/giotto_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
arpack                    3.7.0                hdefa2d7_2    conda-forge
binutils_impl_linux-64    2.40                 hf600244_0    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
ca-certificates           2023.11.17           hbcca054_0    conda-forge
contourpy                 1.2.0                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
fonttools                 4.46.0                   pypi_0    pypi
gcc                       13.2.0               h574f8da_2    conda-forge
gcc_impl_linux-64         13.2.0               h338b0a0_3    conda-forge
glpk                      5.0                  h445213a_0    conda-forge
gmp                       6.3.0                h59595ed_0    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
igraph                    0.10.4               hb9ddf80_2    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_16    conda-forge
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
leidenalg                 0.9.0           py310hd8f1fbe_1    conda-forge
libblas                   3.9.0           20_linux64_openblas    conda-forge
libcblas                  3.9.0           20_linux64_openblas    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-devel_linux-64     13.2.0             ha9c7c90_103    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgfortran-ng            13.2.0               h69a702a_3    conda-forge
libgfortran5              13.2.0               ha4646dd_3    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libhwloc                  2.9.1                hd6dc26d_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblapack                 3.9.0           20_linux64_openblas    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.25          pthreads_h413a1c8_0    conda-forge
libsanitizer              13.2.0               h7e041cc_3    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxml2                   2.10.4               hfdac1af_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
matplotlib                3.8.2                    pypi_0    pypi
metis                     5.1.0             h59595ed_1007    conda-forge
mpfr                      4.2.1                h9458935_0    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
networkx                  2.8.8              pyhd8ed1ab_0    conda-forge
numpy                     1.26.2          py310hb13e2d6_0    conda-forge
openssl                   3.2.0                hd590300_1    conda-forge
packaging                 23.2                     pypi_0    pypi
pandas                    1.5.1           py310h769672d_1    conda-forge
pillow                    10.1.0                   pypi_0    pypi
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.1                    pypi_0    pypi
python                    3.10.2          hc74c709_4_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-igraph             0.10.2          py310h18f4e01_1    conda-forge
python-louvain            0.16                     pypi_0    pypi
python_abi                3.10                    4_cp310    conda-forge
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
scikit-learn              1.1.3           py310h0c3af53_1    conda-forge
scipy                     1.11.4          py310hb13e2d6_0    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smfishhmrf                1.3.3                    pypi_0    pypi
sqlite                    3.44.2               h2c6b66d_0    conda-forge
suitesparse               5.10.1               h9e50725_1    conda-forge
sysroot_linux-64          2.12                he073ed8_16    conda-forge
tbb                       2021.9.0             hf52228f_0    conda-forge
texttable                 1.7.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.2.0              pyha21a80b_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
```

**Comment by szhorvat** [comment]
I'm not affiliated with Giotto, but I've seen different manifestations of the same issue many times. The frank answer here is that using CentOS, especially CentOS 7, in 2023, is setting yourself up for failure. Sadly, there are too many sysadmins out there who refuse to update, causing major inconvenience for all their users.

CentOS 7 uses _extremely_ outdated components. Software compiled for modern (or even quite outdated) Linux systems will not run on CentOS 7.  You need to compile things specifically for CentOS 7 (if they compile at all). This basically rules out using precompiled packages from most sources, including Conda / Conda Forge.

**Comment by RubD** [comment]
@wwang-chcn could your full Conda workflow solve this issue? 

Although it sounds that @szhorvat might have already tried this and that it is a CentOS 7 specific issue.

@josschavezf a new Docker or Singularity image might also solve these problems in the future

**Comment by rbutleriii** [comment]
Thanks @RubD , I would be interested in the full conda option, I imagine I would need to build a conda skeleton for each github R package and host them somewhere, which is doable, but a private solution as it depends on a self hosted conda repo that would have to be maintained.

It's less of a CentOS issue than a University cluster issue. When it was launched a decade ago CentOS 7 was fairly up to date, but clusters don't often (or even ever) rebuild the OS as that is a major project impacting thousands of users. I imagine this is going to impact a significant number of academic Giotto users as they scale past what their laptop can do. For instance I cannot pull in my snRNAseq dataset and my CosMx data set and attempt any kind of integrated analysis without 100GB of memory. 

One of the frequent solutions is lmod, which is as it happens a similar mindset to conda: leave the OS core minimally changed and function on virtual environments. In this case, if I am guessing correctly, they compiled the shared R versions with an older gcc, and so the missing libraries. They do keep it current though, for instance in order for reticulate to work they package a version of python in the module. The cluster admins are pretty responsive, so hopefully they can just update the R environment with newer libraries.

Similar to that, a Singularity solution may also work, but Docker is categorically banned for security reasons on the few campus clusters I have used.

**Comment by wwang-chcn** [comment]
Hi @rbutleriii , here is our conda installation draft. We have installed Giotto using it on a CentOS cluster and would wrap up it into our tutorial later. Please let us know if you have any problem. 

# Installation within conda env

### Clean up (Bash)

-   Clean conda temporary files

    ```bash
    conda clean -a
    ```

-   Clean pip temporary files

    ```bash
    pip cache purge
    ```


## Create conda env (Bash)

```bash
conda create -y -n giotto_suite python=3.10 r=4.2
conda activate giotto_suite

export PKG_CONFIG_PATH=$CONDA_PREFIX/envs/giotto_suite/lib/pkgconfig
# export PKG_CONFIG_PATH=/sc/arion/work/wangw32/conda-env/envs/giotto_suite_bento_install/lib/pkgconfig

```



## Install additional packages (Bash)

These dependency packages are more likely to have errors during Giotto installation due to network issues. We can install those using conda.

```bash
conda install -y -c conda-forge -c bioconda -c r -c defaults r-gert

conda install -y -c conda-forge -c bioconda -c r -c defaults r-magick r-terra r-igraph

conda install -y -c conda-forge -c bioconda -c r -c defaults r-r.utils

conda install -y -c conda-forge -c bioconda -c r -c defaults r-bit64

conda install -y -c conda-forge -c bioconda -c r -c defaults r-scattermore

conda install -y -c conda-forge -c bioconda -c r -c defaults r-sf
```



## Check R_LIB (R)

```R
library_paths <- .libPaths()
print(library_paths)
# [1] "/sc/arion/work/wangw32/conda-env/envs/giotto_suite/lib/R/library"
```



## Install devtools & Giotto (R)

```R
# Necessary for installation from R
if(!"devtools" %in% installed.packages()) {
  install.packages("devtools")
}

options(timeout=1000)
devtools::install_github("drieslab/Giotto")
# update all packages
```



## Install python packages (Bash)

### with pip in bash

```bash
conda activate giotto_suite
conda install -y cmake
pip install pandas python-igraph networkx python-louvain leidenalg scikit-learn smfishHmrf

# install bento if you need it
pip install git+https://github.com/wwang-chcn/bento-tools.git

# install other python packages

```



# Add R to jupyter kernel (Optional)

## install jupyter (Bash)
```bash
conda install -y -c conda-forge -c bioconda -c r -c defaults r-irkernel
conda install -y -c conda-forge -c bioconda -c r -c defaults jupyter
```

## Set up R kernel (R)
```R
install.packages("IRkernel")
IRkernel::installspec(       
       name = "ir4.2GiottoSuiteV4",
       displayname = "R 4.2 Giotto Suite v4"
     )
```

**Comment by rbutleriii** [comment]
@wwang-chcn , I will want to try that as the most portable option. Though I did find the solution to my problem. I am aware of issue #139  where specifying the path to the missing libraries should be easy enough, and it bugged me that I saw `libstdcxx-ng` in the `giotto_env` build. I had tried that `LD_LIBRARY_PATH` solution and it hadn't worked. But then it hit me, put the `giotto_env/lib` at the front not the back, and long story short, if you
```sh
export LD_LIBRARY_PATH=~/.local/share/r-miniconda/envs/giotto_env/lib:$LD_LIBRARY_PATH
```
before you start `R`, it will find the correct libraries first and complete the Clustering tutorial. 

It did take a few seconds longer to `load(Giotto)`, and the `doLeidenSubCluster()` step took a good bit of time (20-30 minutes). I don't know if R is running slower this way since it wasn't compiled with the same libraries the conda env has, but I can compare that to the all-conda install and see which is faster.  

Also, at some point I will try if you can just modify the `giotto_env` activation/deactivation scripts to adjust the library path [on the fly](https://stackoverflow.com/questions/46826497/conda-set-ld-library-path-for-env-only)

**Comment by rbutleriii** [comment]
Checking the speeds, first for the `LD_LIBRARY_PATH` patched version in the default location:
```r
library(Giotto)
library(GiottoData)

x = loadGiottoMini("visium")
microbenchmark::microbenchmark(
  x = doLeidenCluster(x, resolution = 0.4, n_iterations = 1000), 
  times=10
)

Unit: seconds
 expr      min       lq     mean   median       uq      max neval
    x 2.580612 2.609402 2.730969 2.686062 2.823378 3.020799    10
```
Now the `conda` full install:
```r
library(Giotto)
library(GiottoData)

env = system("echo $CONDA_PREFIX", intern=T)
x = loadGiottoMini("visium", python_path=file.path(env, "bin/python"))
microbenchmark::microbenchmark(
  x = doLeidenCluster(x, resolution = 0.4, n_iterations = 1000), 
  times=10
)
Unit: seconds
 expr      min       lq    mean   median       uq      max neval
    x 11.81241 12.07238 12.1795 12.15946 12.25767 12.64387    10
```

Worth noting that for the conda install to get the `.libPaths()` right, you will probably want to add activate.d/deactivate.d scripts that will `unset` your `R_LIBS` and `R_LIBS_USER` variables right before the `Check R_LIB (R)` step:
```sh
# unset the R_LIBS and save for deactivate, $CONDA_PREFIX requires giotto_suite env be activated
printf "%s\n" \
  'old_R_LIBS=$R_LIBS' \
  'old_R_LIBS_USER=$R_LIBS_USER' \
  'unset R_LIBS' \
  'unset R_LIBS_USER' \
  > $CONDA_PREFIX/etc/conda/activate.d/fix.sh

# restore the R_LIBS
printf "%s\n" \
  'R_LIBS=$old_R_LIBS' \
  'R_LIBS_USER=$old_R_LIBS_USER' \
  'unset old_R_LIBS' \
  'unset old_R_LIBS_USER' \
  > $CONDA_PREFIX/etc/conda/deactivate.d/fix.sh
```
Also, the pip install step with of leidenalg did fail with [this](https://stackoverflow.com/q/77642561) error. But exiting out and restarting the shell the next day it moved forward with the following error:
```sh
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
python-igraph 0.11.3 requires igraph==0.11.3, but you have igraph 0.10.8 which is incompatible.
```
`conda install leidenalg` was able to handle it. Running `pip install` with the remaining packages without leiden also had errors:
```sh
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cell2cell 0.6.5 requires tqdm, which is not installed.
cell2cell 0.6.5 requires umap-learn, which is not installed.
gseapy 1.0.3 requires requests, which is not installed.
scanpy 1.9.1 requires numba>=0.41.0, which is not installed.
scanpy 1.9.1 requires tqdm, which is not installed.
scanpy 1.9.1 requires umap-learn>=0.3.10, which is not installed.
```
@wwang-chcn Are those going to be an issue? Those (`cell2cell`, `gseapy`, `scanpy`) aren't installed in the env currently.

 
I was going to go ahead and close this since the problem is solved, with two solutions. The conda environment takes a while to build and run (I recall this being common with `conda` `R` versus a system compiled `R`), but is more portable.

**Comment by rbutleriii** [comment]
Also FYI, for an `LD_LIBRARY_PATH` patched install, you can modify the activate/deactivate scripts, similarly to the full conda install:
```sh
# Run once after install: conda config --append envs_dirs ~/.local/share/r-miniconda/envs/
conda activate giotto_env

# unset the R_LIBS and save for deactivate, $CONDA_PREFIX requires giotto_suite env be activated
printf "%s\n" \
  'old_ret_py=$RETICULATE_PYTHON' \
  'unset RETICULATE_PYTHON' \
  'old_ldpath=$LD_LIBRARY_PATH' \
  'export LD_LIBRARY_PATH=~/.local/share/r-miniconda/envs/giotto_env/lib:$LD_LIBRARY_PATH' \
  > $CONDA_PREFIX/etc/conda/activate.d/fix.sh

# restore the R_LIBS
printf "%s\n" \
  'RETICULATE_PYTHON=$old_ret_py' \
  'unset old_ret_py' \
  'export LD_LIBRARY_PATH=$old_ldpath' \
  'unset old_ldpath' \
  > $CONDA_PREFIX/etc/conda/deactivate.d/fix.sh
```
This also unsets any default `RETICULATE_PYTHON` path, if that is preventing Giotto from pointing your `reticulate` in the right direction. On the cluster I can now just run:
```sh
ml R/4.2.2
conda activate giotto_env
R, Rscript, etc....
```
